import type { Metadata } from "next";
import { Inter ,Montserrat} from "next/font/google";
import "@/app/globals.css";
import Header from "@/app/ui/header";
import Footer from "@/app/ui/footer";

const inter = Inter({ subsets: ["latin"] });

const montserrat = Montserrat({});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body className={inter.className}>
        <Header clas/>
        {children}
        <Footer />
      </body>
    </html>
  );
}
